// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");

function set(array, index, map) {
  return Belt_Array.mapWithIndexU(array, (function (i, value) {
                if (i === index) {
                  return Curry._1(map, value);
                } else {
                  return value;
                }
              }));
}

exports.set = set;
/* No side effect */
