// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("@rescript/std/lib/js/curry.js");

function map(promise, fn) {
  return promise.then(function (v) {
              return Promise.resolve(Curry._1(fn, v));
            });
}

function flatMap(promise, fn) {
  return promise.then(Curry.__1(fn));
}

function failMap(promise, fn) {
  return promise.catch(function (v) {
              return Promise.resolve(Curry._1(fn, v));
            });
}

exports.map = map;
exports.flatMap = flatMap;
exports.failMap = failMap;
/* No side effect */
