// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var message = "The color is " + String(2);

var color = 2;

exports.color = color;
exports.message = message;
/* message Not a pure module */
