// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("rescript/lib/js/belt_Array.js");

function make(id, maxPlayer) {
  return {
          id: id,
          maxPlayer: maxPlayer,
          players: []
        };
}

function isFull(t) {
  return t.players.length >= t.maxPlayer;
}

function addPlayer(t, player) {
  return {
          id: t.id,
          maxPlayer: t.maxPlayer,
          players: Belt_Array.concat(t.players, [player])
        };
}

exports.make = make;
exports.isFull = isFull;
exports.addPlayer = addPlayer;
/* No side effect */
