// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function make(id, damage) {
  return {
          id: id,
          damage: damage
        };
}

exports.make = make;
/* No side effect */
