// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var MatterJs = require("matter-js");

var match = MatterJs.Body;

var Body = {
  setVelocity: match.setVelocity
};

var match$1 = MatterJs.Bodies;

var Bodies_rectangle = match$1.rectangle;

var Bodies_circle = match$1.circle;

var Bodies_fromVertices = match$1.fromVertices;

var Bodies = {
  rectangle: Bodies_rectangle,
  circle: Bodies_circle,
  fromVertices: Bodies_fromVertices
};

var match$2 = MatterJs.Composite;

var Composite_add = match$2.add;

var Composite_remove = match$2.remove;

var Composite = {
  add: Composite_add,
  remove: Composite_remove
};

exports.Body = Body;
exports.Bodies = Bodies;
exports.Composite = Composite;
/* match Not a pure module */
