// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("@rescript/std/lib/js/curry.js");

function mapHp(param_0) {
  return /* MapHp */{
          _0: param_0
        };
}

function make(id, hp) {
  return {
          id: id,
          hp: hp
        };
}

function step(t, action) {
  return {
          id: t.id,
          hp: Curry._1(action._0, t.hp)
        };
}

function isAlive(t) {
  return t.hp > 0;
}

exports.mapHp = mapHp;
exports.make = make;
exports.step = step;
exports.isAlive = isAlive;
/* No side effect */
