// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var zero = {
  x: 0,
  y: 0
};

function create(x, y) {
  return {
          x: x,
          y: y
        };
}

function plus(a, b) {
  return {
          x: a.x + b.x,
          y: a.y + b.y
        };
}

function minus(a, b) {
  return {
          x: a.x - b.x,
          y: a.y - b.y
        };
}

function mult(a, k) {
  return {
          x: a.x * k,
          y: a.y * k
        };
}

function rotate(a, alpha) {
  var sinA = Math.sin(alpha);
  var cosA = Math.cos(alpha);
  return {
          x: cosA * a.x - sinA * a.y,
          y: sinA * a.x + cosA * a.y
        };
}

function mag2(a) {
  return a.x * a.x + a.y * a.y;
}

function mag(a) {
  return Math.sqrt(mag2(a));
}

function norm(a) {
  var magA = Math.sqrt(mag2(a));
  if (magA === 0) {
    return zero;
  } else {
    return mult(a, 1 / Math.sqrt(mag2(a)));
  }
}

function lerp(a, b, v) {
  return {
          x: (a.x + b.x) * v,
          y: (a.y + b.y) * v
        };
}

function dot(a, b) {
  return a.x * b.x + a.y * b.y;
}

exports.zero = zero;
exports.create = create;
exports.plus = plus;
exports.minus = minus;
exports.mult = mult;
exports.rotate = rotate;
exports.mag2 = mag2;
exports.mag = mag;
exports.norm = norm;
exports.lerp = lerp;
exports.dot = dot;
/* No side effect */
