// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Frames$Netgame = require("./Frames.bs.js");

function step(t, action) {
  if (action.TAG === /* Ack */0) {
    return {
            id: t.id,
            clientAck: action._0,
            frames: t.frames
          };
  } else {
    return {
            id: t.id,
            clientAck: t.clientAck,
            frames: Frames$Netgame.step(t.frames, action._0)
          };
  }
}

exports.step = step;
/* No side effect */
