// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Match$Netgame = require("./Match.bs.js");

var match = {
  contents: Match$Netgame.newMatch
};

exports.match = match;
/* Match-Netgame Not a pure module */
