// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function fnv32(s) {
  var len = s.length;
  var _hash = -2128831035;
  var _i = 0;
  while(true) {
    var i = _i;
    var hash = _hash;
    if (i === len) {
      return hash;
    }
    _i = i + 1 | 0;
    _hash = Math.imul(hash ^ (s.charCodeAt(i) | 0), 16777619);
    continue ;
  };
}

function hashId(rInfo) {
  return fnv32("" + rInfo.address + ":" + rInfo.port);
}

exports.fnv32 = fnv32;
exports.hashId = hashId;
/* No side effect */
