// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class Pos {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):Pos {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

x():number {
  return this.bb!.readInt16(this.bb_pos);
}

y():number {
  return this.bb!.readInt16(this.bb_pos + 2);
}

static sizeOf():number {
  return 4;
}

static createPos(builder:flatbuffers.Builder, x: number, y: number):flatbuffers.Offset {
  builder.prep(2, 4);
  builder.writeInt16(y);
  builder.writeInt16(x);
  return builder.offset();
}


unpack(): PosT {
  return new PosT(
    this.x(),
    this.y()
  );
}


unpackTo(_o: PosT): void {
  _o.x = this.x();
  _o.y = this.y();
}
}

export class PosT {
constructor(
  public x: number = 0,
  public y: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return Pos.createPos(builder,
    this.x,
    this.y
  );
}
}
