// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("@rescript/std/lib/js/belt_Array.js");
var Tests$Netgame = require("../lib/Tests.bs.js");
var Frames$Netgame = require("./Frames.bs.js");
var Payload$Netgame = require("./Payload.bs.js");
var ImmuArray$Netgame = require("../lib/ImmuArray.bs.js");
var ClientData$Netgame = require("./ClientData.bs.js");

var sendData_myFrames = {
  end: 3,
  payloads: ImmuArray$Netgame.make([
        Payload$Netgame.nope,
        Payload$Netgame.nope
      ])
};

var sendData_otherAcks = [
  3,
  0
];

var sendData = {
  myIndex: 1,
  myFrames: sendData_myFrames,
  otherAcks: sendData_otherAcks
};

Tests$Netgame.run([
      [
        "TestClientData.res",
        10,
        13,
        82
      ],
      "serialize and deserialize sendData should be the same as do nothing"
    ], ClientData$Netgame.deserializeSend(ClientData$Netgame.serializeSend(sendData)), Tests$Netgame.equal, sendData);

var receiveData_players = Belt_Array.make(5, Frames$Netgame.nope(undefined));

var receiveData = {
  serverAck: 20,
  players: receiveData_players
};

Tests$Netgame.run([
      [
        "TestClientData.res",
        20,
        13,
        85
      ],
      "serialize and deserialize receiveData should be the same as do nothing"
    ], ClientData$Netgame.deserializeReceive(ClientData$Netgame.serializeReceive(receiveData)), Tests$Netgame.equal, receiveData);

exports.sendData = sendData;
exports.receiveData = receiveData;
/* sendData Not a pure module */
