// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Vec2$Netgame = require("../engine/Vec2.bs.js");

function step(param, dt) {
  var transform = param[1];
  var t = param[0];
  var v = t.velocity;
  var a = t.acceleration;
  var maxSpeed = t.maxSpeed;
  var velocity = Vec2$Netgame.plus(v, Vec2$Netgame.mult(a, dt));
  var velocity$1 = Vec2$Netgame.mag2(velocity) > 1 ? velocity : Vec2$Netgame.zero;
  var velocity$2 = Vec2$Netgame.mag(velocity$1) > maxSpeed ? Vec2$Netgame.mult(Vec2$Netgame.norm(velocity$1), maxSpeed) : velocity$1;
  var p = transform.position;
  var position = Vec2$Netgame.plus(p, Vec2$Netgame.mult(velocity$2, dt));
  return [
          {
            velocity: velocity$2,
            acceleration: t.acceleration,
            maxSpeed: t.maxSpeed
          },
          {
            position: position,
            rotation: transform.rotation,
            scale: transform.scale
          }
        ];
}

exports.step = step;
/* No side effect */
